### PR TITLE
compiation fix and _isTable cleanup

### PR DESCRIPTION
**Pull request by seyko2**

### CODE REVIEW

**Comment by jmalak** [comment]
Thanks for your contribution.
I have a few notes.
- you should separate each change to different local branch and create separate pull request, now I must merge/pick each change manualy
- change can not remove some feature, it should be complete (I mean FN_WANT_LAST_PATH value)

Now I integrated build fix. Later I will merge others.

**Comment by seyko2** [comment]
> you should separate each change to different local branch and create separate pull request
It's my second time on pull request on github.

> change can not remove some feature, it should be complete (I mean FN_WANT_LAST_PATH
> value)
This is not a removal. I don;t found a way to get it compiled

**Comment by jmalak** [comment]
I understand. It is only notes for you for future contribution.
Please, if there is something what you are not able to do then open issue on Github and try to discuse solution. If we agree then anybody can correct it after submitting if we know about it.
Uncomment any part of working/used code is very danger because I or any other can overlook it.

**Comment by jmalak** [comment]
Anyway, I get my Linux up and check vi there.
It is bug in vi script processing, variables are expand incorrectly under some conditions.
I will fix it ASAP.

**Comment by seyko2** [comment]
> t is bug in vi script processing, variables are expand incorrectly under some conditions.
> I will fix it ASAP.

Nice, But it looks that default value for gadget string on unix must be changed.

**Comment by jmalak** [comment]
it is fixed now.

**Comment by jmalak** [comment]
fix for vi window border - new fixes were created and applied (for ASSIGN, SET and GADGETSTRING commands)
fix for ui sample build - reworked and applied
fixes for ui projects are under review

**Comment by seyko2** [comment]
> fixes for ui projects are under review
  cd bld/ui/unix/linux386
  wmake sample.exe
  ./sample.exe (on X11/Konsole/xterm)
Then play with console window size

**Pull request closed without merging**
