### PR TITLE
WIP: C++ compiler - changes for ppc and mips architectures

### PR DESCRIPTION
**Pull request by winspool**
I used the same size as ow is using in the c compiler

--
Regards ... Detlef

### CODE REVIEW

**Comment by winspool** [comment]
For the rest, i mostly changed "_CPU == _AXP" to "_RISC_CPU",
but is that the prefered way to solve the rest of the build failures?

* Probably defining and using a "_32BIT_CPU" is better

* With my change to "#if _INTEL_CPU || ( _RISC_CPU )",
  the related code path is always used.
  Is removing the "#if" check a better solution? 


By applying the rest of the patchset, wppmps and wppppc
are build and start to work.
 
[0000_rest_for_wppmps_and_wppppc.txt](https://github.com/open-watcom/open-watcom-v2/files/12580354/0000_rest_for_wppmps_and_wppppc.txt)

**Comment by jmalak** [comment]
We don't want to mask the problems, the problems must be solved.
Replacing the Alpha architecture condition with the _RISC_CPU macro is not a good idea.
Each such condition has a reason, you need to study the code and decide on a solution.
AXP, PPC and MIPS are different architectures with different features.

**Comment by winspool** [comment]
> We don't want to mask the problems, the problems must be solved.
> Replacing the Alpha architecture condition with the _RISC_CPU macro is not a good idea.

That was also my idea, and for that reason, the problematic "_RISC_CPU" changes
are not included in this pull request,
but i attached them as a diff, so everyone can see the current status.

Please commit the clean changes in this pull request 
to make research and testing a lot easier

> Each such condition has a reason, you need to study the code and decide on a solution.
> AXP, PPC and MIPS are different architectures with different features.

I will do that.

**Comment by jmalak** [comment]
Please rebase it to OW2 HEAD and fix a problems if any.

**Review by jmalak — COMMENTED** [review]
If any change related to precompiled header file processing then change minor version to invalidate already created PCH

**Pull request merged**
