### PR TITLE
On Linux, call stat64() even from the stat() function to work around limitations with the i386 Linux kernel stat syscall on 64-bit kernels.

### PR DESCRIPTION
**Pull request by joncampbell123**
This is a fix for https://github.com/open-watcom/open-watcom-v2/issues/752

### CODE REVIEW

**Comment by jmalak** [comment]
Please remove guard for conditional code, I think it is useless.
Remove _BSD_SOURCE macro too.

**Comment by joncampbell123** [comment]
_BSD_SOURCE is needed for the major() and minor() macros when checking st_dev and st_rdev.

It is wrapped in an #ifdef so you can comment out the #define and get the old stat() behavior back very easily.

Should I still remove the guard, make the stat64 behavior the only behavior?

**Comment by jmalak** [comment]
I think it is not covered by POSIX.
I don't want relate to BSD any way for Linux implementation.
What about <sys/sysmacros.h> on Linux to map dev ID's?

**Comment by jmalak** [comment]
To the guard, I don't think that we will return back to old functionality.
There is detailed description why it is done that if it is real problem then we can remove it  or change it somehow.
The use of stat system call is included if stat64 fails that it is OK.

**Comment by joncampbell123** [comment]
sys/sysmacros.h is in my /usr/include/linux directory but Open Watcom doesn't see it while compiling itself, so I'll remove the major, minor checks. I think both stat and stat64 use the same data type for st_dev and st_rdev so it should be OK to copy through. The kernel stat() limits to 255, 255 for legacy reasons, but we don't have to.

I'll remove the conditional part.

**Comment by jmalak** [comment]
It is not a problem. I will remove appropriate macros from sys/types.h and add sys/sysmacros.h to OW to use same code base and users could use it to correct manipulation with major/minor number of device.

**Pull request merged**
