### PR TITLE
New, original implementation of POSIX threads for Linux platform

### PR DESCRIPTION
**Pull request by ArmstrongJ**
This rather large pull request implements the entire POSIX threads API for the Linux platform.  The pull request is a single, squashed commit based on [the posix-thread-1 branch of ArmstrongJ/open-watcom-v2](https://github.com/ArmstrongJ/open-watcom-v2/tree/posix-thread-1), a series of 29 commits that have been rebased to current master.

The threading implementation relies on two major components: Open Watcom's internal threading system (bld/clib/mthread) and POSIX semaphores.  Mutexes, for example, rely on a pair of semaphores for handling locking in a reliable manner.  POSIX threads are accounted for internally in a linked list within the process separate from Open Watcom's internal accounting of threads.  Most other blocking functionality derives from mutexes (with the exception of spinlocks, which rely on some Linux-specific atomic operations).

Although this implementation might be simplistic, it should be easy to port to any other supported platform as long as POSIX semaphores are ported first.  Thread launching is handled by Open Watcom's mthread library, and the code makes no assuumptions about the platform.  If so desired, someone could implement POSIX semaphore wrappers around Windows or OS/2 semaphores, and this threading implementation should "just work" (although some attributes related to scheduling won't).

This pull request is rather large, but it is almost entirely new code.  It shouldn't cause any side effects.

I'm open to comments!  As I stated, this implementation is rather simplistic, but it should work properly.  I have tested it to some degree, obviously, and it seems to be working.

### CODE REVIEW

**Comment by ArmstrongJ** [comment]
Looks like Travis failed in bld/hdr/dos.  Any ideas?

**Comment by staalmannen** [comment]
Very impressive! If it also can be used as a pthreads implementation on Win32, that could be quite useful for (cross-) compiling various open source software for Windows.

**Comment by jmalak** [comment]
Great job, thanks for your effort.
I have a question to this change
`sw_c_linux_386    = -oaxt-D__MT_`
`__MT_ `macro is not used anywhere. Probably it is typo and should be `__MT__`.

**Comment by ArmstrongJ** [comment]
@jmalak good catch.  The typo was introduced during rebasing.

@staalmannen that was the idea.  I wanted to keep the implementation generic enough that porting to other platforms wouldn't be a nightmare.  Also, unlike GNU libc or musl, it makes no particular assumptions about the processor architecture (other than relying on POSIX semaphores), which keeps the code simpler.

**Comment by jmalak** [comment]
From Travis output
**** WSPLICE ERROR **** ../watcom/sys/types.mh, line 40 Can not open 'schedp.sp'
you forgot add schedp.sp file to your pull request.

**Comment by ArmstrongJ** [comment]
Oops, I sure did!  I guess I should have tried a build on a clean system.

**Comment by ArmstrongJ** [comment]
Travis is now failing in causway:

```
= 19:09:52 /home/travis/build/open-watcom/open-watcom-v2/bld/causeway/cwc/linux386 ==
cp ../../cw32/dosi86/cwstub.exe cwstub.exe
bld_cl ./mkcode.exe
bld_as copystub.obj
bld_link copystub.tmp
./mkcode.exe copystub.gh
bld_as decstub.obj
bld_link decstub.tmp
./mkcode.exe decstub.gh
cc cwc.obj
link cwc.exe
Error! E2028: _errno is an undefined reference
Error! E2028: __InitThreadData_ is an undefined reference
Error! E2044: exported symbol _errno not found
Error! E2044: exported symbol __InitThreadData_ not found
Error(E42): Last command making (cwc.exe) returned a bad status
Error(E02): Make execution terminated
<pmake -d build          -h> => non-zero return: 512
Build failed
```

I don't really have any thoughts on why this error is occurring.   Anyone have any ideas?

**Comment by jmalak** [comment]
If I remember properly then for linux was not used -bm option only __MT__ macro for few files with multi-threaded support. Due to not implemented multi-threaded stuff it is running in single threaded mode only. It will require to implement full multi-threaded support, by example errno, stack etc. must be separated for each thread. It is mostly defined by macros in bld/lib_misc/rt.....h header files if  __MT__ macro is defined. It looks like you should not use __MT__ macro defined globaly on Linux now, you should define it only on file level (if it should be defined) until full multi-threaded support will be implemented for Linux and __MT__ macro can be defined globaly.

**Comment by ArmstrongJ** [comment]
I'm not sure I understand your response.  Defining `__MT__` should enable the thread-specific errno, etc. in rterrno.h and other rt hearders, correct?

I think `__MT__` needs to be defined globally on Linux.  It's not working is a bug in how `__MT__` itself is dealt with.  Defining `__MT__` all over the place just for Linux would be a terrible idea.  Some of the changes I had made to mthread should have resulted in a fully multithreading-capable runtime on Linux.

Oddly enough, I am not getting a build error after cleaning in causeway, but I am building with a 2.0 distro with fresh libraries.

I'll investigate further on my end and see if I can both replicate and fix the issue.  Stay tuned.

**Comment by jmalak** [comment]
I agree that final state is to use __MT__ on Linux globaly, but due to unfinished full multi-threaded stuff in run-time library is not possible to do it immediately. It is what I mean that __MT__ macro should be used selectively in place where real multi-threaded stuff is deployed. As soon as full multi-threade stuff will be available then it can be changed. Take into account dependency of Fortran and C++ run-time library on CRTL. They must be also fixed.

**Comment by jmalak** [comment]
I will try to clone your repository to my box and try to compile it and look on your code a little bit deaper and do pull request to your repository to help you.

**Comment by ArmstrongJ** [comment]
@jmalak I'll be looking into the build failures soon, but there are changes in mthread to support multithreading on Linux.  Most notably, input/output blocking is handled the same way it is handled on Windows.  A few missing definitions that were marked "TODO" for Linux were filled in properly. I'll look into what else is missing.  But if it's anything less than full multithreading runtime support, this pull request should probably be pulled down and abandoned.  It would be absurd to offer POSIX threads otherwise.

**Comment by jmalak** [comment]
OK. It is little harder to do it in one big step to get full multi-threaded stuff then in partial steps.

**Comment by jmalak** [comment]
OK. It is little harder to do it in one big step to get full multi-threaded stuff then in partial steps.

**Comment by jmalak** [comment]
Sorry, I forgot add comment.
What can be changed in OW2 I did in OW2 master branch by change 0c62a545dd9655df83b532f3d98c46a66ec798dd.
You must merge your branch with OW2 master branch to be up-to-date.
There will be many conflict due to replacement `__MT__ `macro by `__SW_BM`. 
`__SW_BM `macro is now correct for `C/C++` code and only -bm option is correct for make files.
`__MT__ `macro is not used for `C/C++` anymore in RTL code
Before this action you should remove my patch-4 and patch-5 which are now useless.

**Comment by ArmstrongJ** [comment]
I'll need to close this pull request in that case, revert pull requests 4 and 5 on my branch, and rebase locally.  I'll close the pull request when complete and open a new one.

**Comment by jmalak** [comment]
Please, do it. I have a few other changes, but I will push it after you will merge your branch with OW2 master to do these changes more transparent.

**Comment by ArmstrongJ** [comment]
This pull request is superseded by #283

**Pull request closed without merging**
