### PR TITLE
fixed typo in README.md

### PR DESCRIPTION
**Pull request by Th3T3chn0G1t**
`oficial` -> `official`

### CODE REVIEW

**Comment by jmalak** [comment]
Thanks for your contribution.

**Comment by iainnicol** [comment]
Hi @Th3T3chn0G1t, I and a few others are trying to relicense Open Watcom. Currently Open Watcom is under an unusual license, and we want to move it to a more mainstream one. Please see the [wiki](https://github.com/open-watcom/open-watcom-v2/wiki/Relicensing-effort) for an explanation, or this [absolutely massive discussion](https://github.com/open-watcom/open-watcom-v2/discussions/271).

Would you be willing to relicense your contribution, under Apache 2.0, plus the LLVM Exceptions?

(To be honest, your fix, while valuable, is probably too small to be copyrightable. Nonetheless, it would still be useful, and clear, if you would be willing to relicense it.)

**Comment by jmalak** [comment]
I think this file is not part of distribution, only GitHub readme file.

**Comment by iainnicol** [comment]
that's true, but it doesn't hurt for pedantic completeness. i'm just about to go through the v2-only contributors, and so i noticed this most recent commit.

**Comment by jmalak** [comment]
It is not Original source, it is OW Contributors source only, that don't need re-licencing by SAP.

**Comment by iainnicol** [comment]
I disagree. I'll send you an email tomorrow to try to explain.

**Comment by Th3T3chn0G1t** [comment]
@iainnicol sure lol - my single letter `f` perhaps unwarranted kwk

**Pull request merged**
