### PR TITLE
readme.txt: minor spelling and grammar fixes (pull request try #3)

### PR DESCRIPTION
**Pull request by ideafarm**
Finally, on this one I have "Able to merge."

### CODE REVIEW

**Comment by jmalak** [comment]
I am not sure if the readme.txt should be restored.
Peter moved most of information to Wiki and general info is in README.md.

**Comment by ideafarm** [comment]
This commit just fixes a couple of spelling and grammar errors.  I just want to see the GitHub process by which changes are contributed, negotiated, and accepted into a repository using the "fork, branch, and pull" procedure.  The only reason that I'm bothering you with this pull request is so that I can see the procedure.  If you don't accept the pull request, I won't be able to see how it all works.

**Comment by ideafarm** [comment]
I just reread your note.  Did Peter delete the readme.txt file?  If so, then there's something wrong, since the readme.txt file still existed in your master branch when I forked it.  ...  Oh, I get it!  The readme.txt file no longer exists in your master!  You must have deleted it within the past few days.  That explains why it used to appear on the GitHub page for the repository, which now displays readme.md instead!

I've just experience my first lesson on using GitHub to collaborate.  Is there some way that I could have known that readme.txt was about to be deleted?  I.e., was there some notice somewhere that Peter had "checked out" the file?

**Comment by pchapin** [comment]
I converted the readme.txt to markdown format quite a long time ago. You must be using an old version of the system. Generally you want to do something like

    git pull upstream master

on a regular basis to ensure your working copy is tracking the latest version of things.

More recently (end of April) I moved the bulk of the README contents to the GitHub wiki for this project. It can be edited there (by anyone) or via a separate Git repository.

**Pull request closed without merging**
