### PR TITLE
rc/exedmp: Build the exedmp tool also on i386-linux

### PR DESCRIPTION
**Pull request by winspool**
This tool uses Microsoft specific runtime functions
and needs more fixes for 64bit.

--
Regards ... Detlef

### CODE REVIEW

**Comment by jmalak** [comment]
What sense has OW internal resource tools to be build for Linux if resource compiler can be developed only for Windows and OS/2 and can be tested only on these OS-es?

**Comment by winspool** [comment]
I am working on extending wdump to better support 64bit
and try everything available to look inside any file.

**Comment by jmalak** [comment]
It is OK to extend it to PE 64-bit, but we are talking about Linux build of rcdmp which has no sense.
Anyway wdump already support 64-bit PE header, see exedump/c/peexe.c source file.

**Comment by winspool** [comment]
> It is OK to extend it to PE 64-bit, 
> but we are talking about Linux build of rcdmp which has no sense.

Compiling for Windows is most times done on Linux here.

> Anyway wdump already support 64-bit PE header, see exedump/c/peexe.c source file.

64bit elf support is missing
(64bit macho for looking in armo64 and bino64 is a bonus)

**Pull request closed without merging**
