### PR TITLE
Add a "#warning" preprocessor directive

### PR DESCRIPTION
**Pull request by thentenaar**
This adds #warning for both cc, an plusplus.

### CODE REVIEW

**Comment by jmalak** [comment]
Must make changes, I have the following comments.
- #warning is not defined by any C / C ++ standard, it must be defined as a language extension, not a standard function
- the hash for #warning is too stupid (dangerous), it must be extended to all 3 values per keyword
- symbol names are a little strange, it should be rather self explanation symbols (by example user_msg symbol for function processing #error and #warning directives)

**Comment by jmalak** [comment]
I were thinking about it a little bit.
I don't think that we should implement this.
OW has similar functionality by "#pragma message" which is more suitable then absolutely unportable things as non-standard pre-processor directive `#warning`. 
I don't want follow some stupidity from GCC.

**Comment by fsb4000** [comment]
C23 and C++23 added `#warning`

https://en.cppreference.com/w/cpp/preprocessor/error

https://en.cppreference.com/w/c/preprocessor/error

**Comment by jmalak** [comment]
Thanks for info about C23 standard which include this preprocessor directive to C/C++ standard.
In this case we can include it as extension for lower standards.

**Comment by jmalak** [comment]
Little reworked for better integration as extension.
Submitted as d9181a34

**Pull request closed without merging**
