### PR TITLE
Add Windows NT for MIPS support in clib

### PR DESCRIPTION
**Pull request by lakor64**
The following PR adds Windows NT for MIPS in WATCOM C library, the compilation doesn't currently fully work due to missing CG code (which will be pushed in separate PRs)

- Added clib projects for Windows NT mips
- Added generation of export.tmp (-z flag) for RISC platforms (mps, ppc, axp)
- Implement NT MIPS startup (same as AXP for now)
- Fix heap compilation on non-8086 platform
- Add missing flags to use NT api on MIPS inside libwin32
- Add TGT_SYS check on mthread
- Stub fpu exception implementation for now (I will investigate them and make a PR to either specifiy there's no fpu exceptions or implement the relative code, or in this PR in case it's required)

### CODE REVIEW

**Comment by jmalak** [comment]
Thank you for your contributions.

**Comment by iainnicol** [comment]
Hi @lakor64. We are in the process of changing the Open Watcom license, from its custom license, to a more mainstream one. For a full explanation you can see the [relicensing page](https://github.com/open-watcom/open-watcom-v2/wiki/Relicensing-effort) on the Wiki.

Are you happy to licence your contributions under [Apache 2.0 + LLVM Exceptions](https://llvm.org/LICENSE.txt)? (It's the same licence as used by LLVM and Clang.) It would be fantastic if that's okay with you.

**Comment by lakor64** [comment]
> Hi @lakor64. We are in the process of changing the Open Watcom license, from its custom license, to a more mainstream one. For a full explanation you can see the [relicensing page](https://github.com/open-watcom/open-watcom-v2/wiki/Relicensing-effort) on the Wiki.
> 
> Are you happy to licence your contributions under [Apache 2.0 + LLVM Exceptions](https://llvm.org/LICENSE.txt)? (It's the same licence as used by LLVM and Clang.) It would be fantastic if that's okay with you.

Permission granted! ✅  I would love to see Open Watcom in a better license than the current one

**Comment by iainnicol** [comment]
awesome! thank you.

**Comment by lakor64** [comment]
you can consider the commits I did and possible the future ones approved for the new license as well (I plan to send some others for mips support)

**Pull request merged**
