### PR TITLE
Fix memory errors in wasm

### PR DESCRIPTION
**Pull request by DelilahHoare**
This will be needed on osx arm.

### CODE REVIEW

**Review by jmalak — COMMENTED** [review]
comparison includes null termination byte, therefore this situation cannot happen

**Comment by DelilahHoare** [comment]
> comparison includes null termination byte, therefore this situation cannot happen

memcmp is allowed to read anywhere in the passed ranges, and the popular implementations do use SIMD instructions which can read far past the terminator.  The call causes an error when running with ASAN.

**Comment by jmalak** [comment]
> > comparison includes null termination byte, therefore this situation cannot happen
> 
> memcmp is allowed to read anywhere in the passed ranges, and the popular implementations do use SIMD instructions which can read far past the terminator. The call causes an error when running with ASAN.

It can not compare data after min( len of string1, len of string2 ) + 1 because it always end on first "null" in any of both strings.

**Comment by jmalak** [comment]
> > > comparison includes null termination byte, therefore this situation cannot happen
> > 
> > 
> > memcmp is allowed to read anywhere in the passed ranges, and the popular implementations do use SIMD instructions which can read far past the terminator. The call causes an error when running with ASAN.
> 
> It can not compare data after min( len of string1, len of string2 ) + 1 because it always end on first "null" in any of both strings. How implementation read and process data is not important. C standard is defining behavior of memcmp exactly and implementation must respect it otherwise it is nonconforming implementation.

I looked into standard and you are right, standard doesn't require to stop on first difference. It allows to read full length on both arguments.

**Review by jmalak — COMMENTED** [review]
I think following code could be more transparent
```
            before = start - old_line;
            if( before > 0 ) {
                if( *(start - 1) == '&' )
                    before--;
                strncpy( new_line, old_line, before );
            }
            *(new_line + before) = '\0';
            if( sprintf( buffer, "#%-2.2d", count ) != 3 ) {
                myassert( 0 );
            }
            strcat( new_line, buffer );
```

**Pull request merged**
