### PR TITLE
use POSIX command . instead of "source" command

### PR DESCRIPTION
**Pull request by yamori813**
I build OW on FreeBSD/i386. I have some error. This is fixed patch.

### CODE REVIEW

**Comment by jmalak** [comment]
Thanks for your contribution.
Shell script change, it is OK.
Please remove the next change it is not acceptable.
If wmake build is not working then it must be fixed not to use gmake or is it bug in FreeBSD?
Generally POSIX solution is used if possible. 
Please open issue for wmake build problem, it is most important part of build system that POSIX compatibility is required on *NIX systems.

**Comment by yamori813** [comment]
Thanks comment.

I make original build.sh.

**Comment by jmalak** [comment]
Please add fix for clean.sh together with build.sh.

**Comment by jmalak** [comment]
clean.sh change were submitted.

**Comment by yamori813** [comment]
Thanks.

I put new issue.

https://github.com/open-watcom/open-watcom-v2/issues/666

**Comment by iainnicol** [comment]
Hi @yamori813. こんにちは、日本語に訳すのが下手で申し訳ありません。現在、Open Watcomは奇妙なソフトウェアライセンスを使用しています。私たちはOpen Watcomを「[Apache 2.0 license plus LLVM Exceptions](https://llvm.org/LICENSE.txt)」で再ライセンスしたいと考えています。これで良いのでしょうか？詳しくは[wiki](https://github.com/open-watcom/open-watcom-v2/wiki/Relicensing-effort)をご覧ください。

Hi. Sorry for the bad translation into Japanese. Currently Open Watcom uses a weird software license. We want to relicense Open Watcom under “[Apache 2.0 license plus LLVM Exceptions](https://llvm.org/LICENSE.txt)”. Is this okay with you? Please see the [wiki](https://github.com/open-watcom/open-watcom-v2/wiki/Relicensing-effort) for more information.

**Comment by yamori813** [comment]
Sorry too late reply.

I think good that is change license.

**Comment by iainnicol** [comment]
Thank you :-)

**Pull request merged**
