### PR TITLE
This commit improves x86 assembly code with speed and size optimizations...

### PR DESCRIPTION
**Pull request by javiergutierrezchamorro**
..., mainly consisting on:
- mov <reg>, 0 => xor <reg>, <reg>. When flags are not used it is usually smaller, and faster in 386 or lower CPU.
- cmp <reg>, 0 => test <reg>, <reg>. When flags are not used it is usually smaller, and faster in 386 or lower CPU.
- mov <reg>, -1 => or <reg>, -1. When flags are not used it is usually smaller, and faster in 386 or lower CPU.
- mov <regh>, x, mov <regl>, y => mov regx, x*256+y. Usually smaller and always faster.

Special focus has been put on mathlib and clib. Commit builds OK, and passes all regression tests.

More optimizations would follow.

### CODE REVIEW

**Comment by jmalak** [comment]
It was submitted to git repository as 7728caaba512c3bf091b94fe9e4564558803d77f.
It was reviewed and some other optimization was added to submit as removing operand size prefix for 32-bit code if move to/from segment registers is used. code386.asm was not yet submitted because it need more detailed review with regards to code pipeline pairing in U and V instruction queues.

**Comment by javiergutierrezchamorro** [comment]
Thank you for your review, additions and the integration itself @jmalak 
As for code386.asm will wait, no worries. Take your time for reviewing.

**Comment by sparky4** [comment]
ah i hope these optimizations will be implimented ^^ and cause no problems~

**Comment by javiergutierrezchamorro** [comment]
It was already partially integrated back in 2015: https://github.com/open-watcom/open-watcom-v2/commit/7728caaba512c3bf091b94fe9e4564558803d77f

**Comment by sparky4** [comment]
oh cool!

**Comment by jmalak** [comment]
16-bit code was already deployed. only 32-bit code changes was partialy deployed.
it need some review with regards to pentium optimization rules(I am not much familiare with it)

**Pull request closed without merging**
