### PR TITLE
WIP: Prepare for building wppmps and wppppc on linux

### PR DESCRIPTION
**Pull request by winspool**
This is not complete, but helps fixing the C++ cross compiler for mips and powerpc on a linux host

I have no idea about the best way for windows hosts, so i skipped that

--
Regards ... Detlef

### CODE REVIEW

**Comment by winspool** [comment]
The attached WIP-Patch, allows bwppmps and bwppppc compile
(but linking fails)



[0000_compile_wpp_for_RISC_CPU.txt](https://github.com/open-watcom/open-watcom-v2/files/12448647/0000_compile_wpp_for_RISC_CPU.txt)

**Comment by jmalak** [comment]
I fixed what was necessary.
Please rebase it for OW2 latest git commit.

**Comment by jmalak** [comment]
I added minimal shared RISC stuff for C++ compiler to be compilable.
It should be generic stuff but require review and modify what is necessary for each architecture.
rebase your changes over it.

**Comment by jmalak** [comment]
Please rebase it to OW2 HEAD and fix a problems if any.

**Comment by jmalak** [comment]
After fixing all problems I submit it into OW2 git.

**Pull request merged**
